#!/bin/bash
#SBATCH --nodes=1                   #### Nb de noeuds
#SBATCH --ntasks=4                 #### Nb de taches
#SBATCH --ntasks-per-node=24        #### Nb de coeurs/noeuds ici 24
#SBATCH --threads-per-core=1
#SBATCH --time=24:00:00             #### temps demandé maximum 
#SBATCH --begin=now                 #### calcul commmence au plus tot 
#SBATCH --mail-user=jean.fesquet@isae-supaero.fr #### votre mail
#SBATCH --mail-type=START,FAIL,END        #### mail quand c'est fini ou erreur
#SBATCH --job-name=REPLACETHIS            #### le nom de votre calcul
#SBATCH -o %j.out   #### sortie standard STDOUT
#SBATCH -e %j.err   #### sortie erreur STDERR
#SBATCH --partition=short       #### la partition

########## MODULES ##########

module load python
source activate base

nprocs=$SLURM_NTASKS
nnodes=$SLURM_NNODES
njobcpunode=$SLURM_JOB_CPUS_PER_NODE

echo "NofNodes $nnodes NofTaskPerCpu $njobcpunode NofCpus $nprocs"
#ldd ${FINE_BIN}
python launch.py> out.log 2>&1



